### PR TITLE
Update scripts

### PR DESCRIPTION
**Pull request by Fil**
this is what I had to do to be able to run the scripts.

To run the client I've also had to run
```bash
pip install flask flask_cors
cd python_server
python server.py
```

### CODE REVIEW

**Comment by enjalot** [comment]
I totally missed this PR 2 weeks ago... thanks for trying it out!
I've completely revamped the repo, the process and the ux. I'll be adding more detailed instructions to the README but soon will be as easy as 
```
pip install latent-scope
ls-serve ~/latent-scope-data
```
each of the scripts has an associated command too like
`ls-embed` and `ls-umap`

one main idea is that all processes write to their dataset folder, datasets are kept in LATENT_SCOPE_DATA directory that needs to be set in .env or as an environment variable (running the server with the directory as parameter sets this for you)
then running the scripts individually, also still possible, will lookup the directory from .env

**Comment by Fil** [comment]
I wanted to try the new instructions but I'm stuck at the first line "install the module", because I don't know what I'm supposed to do to install it.

**Comment by enjalot** [comment]
sorry, that's because I haven't actually published the module yet.
you can do `pip install -e .` to install it from source. you'll also need
to npm install and npm run dev in the web/ folder if you want to use the UI

**Comment by Fil** [comment]
Nice! it works!

**Comment by enjalot** [comment]
sweet, I'm hoping to improve the docs and a few more basic features before
officially releasing it sometime next week. any feedback would be
appreciated!

**Pull request closed without merging**
